export class Location {
    _id: string;
    customername: string;
    housenumber: number;
    housenumberaddition: number;
    streetname: string;
    postcode: number;
    city: string;
    country: string;
    kvknumber: number;
    kvkname: string;
    btwnumber: string;     
    onboardingcompleted: string;  
    newsitenumber: number;
    clientaccountnumber: number;
    parentcustomerid: number;
    status: string;
    istestlocation: string;
    sla: string;
    monitoring: string;
    locationopen: string;
    customertypeid: number;    
    billingmodel: string;
    ponumber: string;
    regelreferentie: string;
    chainid :number;
    accountmanagerid:number;
    locationtypeid :number;
    locationnote :string;
    billingid : number;
    comarchcustomerid : string;
    comarchinvoiceaccountid : string;
    comarchcontract : string;
    comarchkrn : string;
    filiaalnummer:string;
    contactinheritance:number;
    contractinheritance:number;
    servicenotesinheritance:number;
  }